name: CI

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Run tests
      run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run cargo audit
      run: |
        cargo install --locked cargo-audit
        cargo audit

  build-release:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install sccache
      uses: mozilla-actions/sccache-action@v0.0.3
    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
    - name: Prepare Windows artifact
      if: runner.os == 'Windows'
      shell: bash
      run: |
        BIN_NAME=kandil_code
        OUT_DIR=target/${{ matrix.target }}/release
        cp "$OUT_DIR/${BIN_NAME}.exe" "${BIN_NAME}-${{ matrix.target }}.exe"
    - name: Upload Windows artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: kandil_code-${{ matrix.target }}
        path: kandil_code-${{ matrix.target }}.exe
    - name: Prepare Unix artifact
      if: runner.os != 'Windows'
      shell: bash
      run: |
        BIN_NAME=kandil_code
        OUT_DIR=target/${{ matrix.target }}/release
        tar -C "$OUT_DIR" -czf "${BIN_NAME}-${{ matrix.target }}.tar.gz" "$BIN_NAME"
    - name: Upload Unix artifact
      if: runner.os != 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: kandil_code-${{ matrix.target }}
        path: kandil_code-${{ matrix.target }}.tar.gz

    - name: Sign Windows executable
      if: runner.os == 'Windows' && env.WIN_SIGN == 'true'
      shell: powershell
      env:
        WIN_SIGN: ${{ secrets.WIN_SIGN }}
        WIN_CERT_PATH: ${{ secrets.WIN_CERT_PATH }}
        WIN_CERT_PASSWORD: ${{ secrets.WIN_CERT_PASSWORD }}
      run: |
        $exe = "kandil_code-${{ matrix.target }}.exe"
        if (Test-Path $exe) {
          & signtool sign /f "$env:WIN_CERT_PATH" /p "$env:WIN_CERT_PASSWORD" /fd SHA256 /tr http://timestamp.digicert.com /td SHA256 "$exe"
        }

    - name: Sign macOS binary
      if: runner.os == 'macOS' && env.MAC_SIGN == 'true'
      shell: bash
      env:
        MAC_SIGN: ${{ secrets.MAC_SIGN }}
        MAC_ID: ${{ secrets.MAC_ID }}
        MAC_TEAM: ${{ secrets.MAC_TEAM }}
      run: |
        BIN_NAME=kandil_code
        OUT_DIR=target/${{ matrix.target }}/release
        codesign --force --sign "$MAC_ID" "$OUT_DIR/$BIN_NAME"

  publish-release:
    needs: build-release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./dist
    - name: Generate checksums
      run: |
        find ./dist -type f \( -name 'kandil_code-*.exe' -o -name 'kandil_code-*.tar.gz' \) -exec sha256sum {} \; > ./dist/checksums.txt
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./dist/**
          ./dist/checksums.txt
        draft: false
        prerelease: false
